name: app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  qr_flutter: ^4.1.0
  flutter_modular: ^6.3.4
  flutter_hooks: ^0.21.2
  mobile_scanner: ^6.0.10
  shared_preferences: ^2.5.3
  add_to_cart_animation: ^2.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/qrs/


